### ISSUE TITLE
Deploy to Fly.io failing

### ISSUE THREAD

**Issue by SimonLab** [dwyl/elixir-auth-github-demo#57]
> Error No access token available. Please login with 'flyctl auth login'

See the action failing for the main branch: https://github.com/dwyl/elixir-auth-github-demo/actions/runs/4162831180/jobs/7202511438

@nelsonic can you add a new `secret` for the Github action to be able to deploy to Fly automatically (https://github.com/dwyl/elixir-auth-github-demo/settings/secrets/actions)

I don't have access to the fly application so my `flyctl auth token` won't work for this repository.

**Comment by nelsonic** [comment]
updated ✅ 
https://github.com/dwyl/elixir-auth-github-demo/settings/secrets/actions
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/194400/218495334-aa661617-872b-4f72-86b7-2052194ae572.png">

**Comment by nelsonic** [comment]
https://fly.io/dashboard/dwyl-elixir-auth-google-demo/team
<img width="594" alt="image" src="https://user-images.githubusercontent.com/194400/218495709-0a5d1357-5ce8-448e-b1ec-7293784ccb03.png">

<img width="866" alt="image" src="https://user-images.githubusercontent.com/194400/218495797-8ab277c1-c587-4e95-8804-be9ba9da5655.png">

You should have received an invite by email. 👍

**Comment by SimonLab** [comment]
Rerun the action to deploy, fixed
