### ISSUE TITLE
Update version of Elixir in Buildpack: elixir_buildpack.config#L5

### ISSUE THREAD

**Issue by nelsonic** [dwyl/elixir-auth-github-demo#7]
Heroku deploy fails because of Elixir version mismatch:
https://dashboard.heroku.com/apps/elixir-auth-github-demo/activity/builds/e32d14b2-6ff1-4d7e-9f3c-263deb7123f5
![image](https://user-images.githubusercontent.com/194400/91546726-d0d0fc80-e91a-11ea-86f6-ff6da366941c.png)

https://github.com/dwyl/elixir-auth-github-demo/blob/01ad4ed61260a888831ec955e1fac3a6dcc16e88/elixir_buildpack.config#L5

**Comment by SimonLab** [comment]
Deployment worked and just tested the app with a private email on Github, working well.

**Comment by nelsonic** [comment]
Thanks for confirming @SimonLab 🙌
